### PR TITLE
Expose feature for shared stdxx on android

### PR DESCRIPTION
**Pull request by NiklasEi**
The cpal feature seems to be needed to get bevy + kira to work on my android phone.

### CODE REVIEW

**Comment by tesselode** [comment]
Is this always going to be needed on Android, or only when using Kira with Bevy? If it's the former, can we just make this a [platform-specific dependency](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies)?

**Comment by NiklasEi** [comment]
I don't think it's always needed, so I would follow the way cpal and bevy expose this via a feature flag.

From the cpal readme:
> Oboe can either use a shared or static runtime. The static runtime is used by default, but activating the oboe-shared-stdcxx feature makes it use the shared runtime, which requires libc++_shared.so from the Android NDK to be present during execution.

**Comment by NiklasEi** [comment]
FYI: the same solution has been taken in rodio now: RustAudio/rodio#546

**Comment by tesselode** [comment]
ok fiiiine i'll merge it

(thank you for your investigation!)

**Pull request merged**
