### PR TITLE
Create examples subproject

### PR DESCRIPTION
**Pull request by joeperri95**
Hey there, 

First of all thanks for making this. It's a great library with a lot of promise. 

This PR contains a super basic sample project using the cargo examples feature. 
There is a lot of sample code in the book and the Readmes but they all require some additional set up to get off the ground.
I thought it might be a good idea to have something someone completely new to the project could use as a starting point.

The check action has also been edited to build examples so it will catch if some new change in the library causes the sample code to break.

### CODE REVIEW

**Comment by tesselode** [comment]
Hi, thanks for the PR!

I'm not sure I want to have binary files in the main repo. It'll be in the history forever, so I want to be conservative about what kind of data is included. At the very least, I wouldn't want to include a 2 minute song when a short sound effect would suffice.

For previous versions of Kira, I had a [separate repo for examples](https://github.com/tesselode/kira-demo). It's not as convenient as having an example in the main repo, though.

Also, I'm not sure if command-line apps are the best way to show how to use Kira. Usually, you'll be using it in a game that has an update loop. When you have one-shot examples, there's a bit of extra boilerplate to make sure the program doesn't exit too early. That's not part of the normal workflow of using Kira, so that may be a distraction from learning the library properly.

**Comment by joeperri95** [comment]
Oh I did not see that separate repo.
That takes care of what this PR is looking to achieve.

**Comment by joseluis** [comment]
@tesselode when I rediscovered this project recently I also missed having quick and easy examples to try things out, so I ended up doing something very similar to this PR just for myself.

I still think it would be nice to have shorts examples to demonstrate specific topics. I'd be happy to go with you over some ideas if you want, maybe in the *discussions* tab of the repo if that was enabled...

**Comment by tesselode** [comment]
@joseluis there is a discussions tab now!

**Pull request closed without merging**
